version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - denoland
  - importantimport
  - lume
  - lumeland
  - masknet
  - moeru
  - nolebase
  - pkgroll
  - sonarjs
  - vitepress
ignoreWords: []
import: []
