version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - bumpp
  - denoland
  - foxts
  - importantimport
  - lume
  - lumeland
  - masknet
  - moeru
  - nolebase
  - pkgroll
  - scule
  - sonarjs
  - sukka
  - unjs
  - vitepress
  - xsai
ignoreWords: []
import: []
