shellEmulator: true

trustPolicy: no-downgrade

packages:
  - docs
  - packages/*

catalog:
  '@antfu/eslint-config': ^7.4.3
  '@masknet/eslint-plugin': ^0.4.1
  '@orama/orama': ^3.1.18
  '@tailwindcss/postcss': ^4.1.18
  '@types/mdx': ^2.0.13
  '@types/node': ^25.2.3
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@vitest/coverage-v8': ^4.0.18
  '@vitest/ui': ^4.0.18
  bumpp: ^10.4.1
  clsx: ^2.1.1
  eslint: ^10.0.0
  eslint-flat-config-utils: ^3.0.1
  eslint-plugin-de-morgan: ^2.0.0
  eslint-plugin-depend: ^1.4.0
  eslint-plugin-oxlint: ^1.46.0
  eslint-plugin-perfectionist: ^5.5.0
  eslint-plugin-prefer-arrow: ^1.2.3
  eslint-plugin-sonarjs: ^3.0.7
  fumadocs-core: 15.6.4
  fumadocs-mdx: 11.6.11
  fumadocs-twoslash: ^3.1.13
  fumadocs-ui: 15.6.4
  jiti: ^2.6.1
  lucide-react: ^0.564.0
  motion: ^12.34.0
  next: 15.4.1
  oxlint: ^1.47.0
  pkgroll: ^2.25.2
  postcss: ^8.5.6
  react: ^19.2.4
  react-dom: ^19.2.4
  remark: ^15.0.1
  remark-gfm: ^4.0.1
  remark-mdx: ^3.1.1
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  tinyexec: ^1.0.2
  tsx: ^4.21.0
  tw-animate-css: ^1.4.0
  twoslash: ^0.3.6
  vitest: ^4.0.18
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
