packages:
  - docs
  - packages/*

catalog:
  '@antfu/eslint-config': ^5.3.0
  '@masknet/eslint-plugin': ^0.4.0
  '@orama/orama': ^3.1.11
  '@tailwindcss/postcss': ^4.1.12
  '@types/mdx': ^2.0.13
  '@types/node': ^24.3.1
  '@types/react': ^19.1.12
  '@types/react-dom': ^19.1.8
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  bumpp: ^10.2.3
  clsx: ^2.1.1
  eslint: ^9.35.0
  eslint-flat-config-utils: ^2.1.1
  eslint-plugin-de-morgan: ^1.3.1
  eslint-plugin-oxlint: ^1.14.0
  eslint-plugin-perfectionist: ^4.15.0
  eslint-plugin-prefer-arrow: ^1.2.3
  eslint-plugin-sonarjs: ^3.0.5
  fumadocs-core: 15.6.4
  fumadocs-mdx: 11.6.11
  fumadocs-twoslash: ^3.1.6
  fumadocs-ui: 15.6.4
  jiti: ^2.5.1
  lucide-react: ^0.542.0
  motion: ^12.23.12
  next: 15.4.1
  oxlint: ^1.14.0
  pkgroll: ^2.15.3
  postcss: ^8.5.6
  react: ^19.1.1
  react-dom: ^19.1.1
  remark: ^15.0.1
  remark-gfm: ^4.0.1
  remark-mdx: ^3.1.0
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.12
  tsx: ^4.20.5
  tw-animate-css: ^1.3.7
  twoslash: ^0.3.4
  vitest: ^3.2.4
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
