packages:
  - docs
  - packages/*

catalog:
  '@antfu/eslint-config': ^6.2.0
  '@masknet/eslint-plugin': ^0.4.1
  '@orama/orama': ^3.1.16
  '@tailwindcss/postcss': ^4.1.17
  '@types/mdx': ^2.0.13
  '@types/node': ^24.10.1
  '@types/react': ^19.2.5
  '@types/react-dom': ^19.2.3
  '@vitest/coverage-v8': ^4.0.9
  '@vitest/ui': ^4.0.9
  bumpp: ^10.3.1
  clsx: ^2.1.1
  eslint: ^9.39.1
  eslint-flat-config-utils: ^2.1.4
  eslint-plugin-de-morgan: ^2.0.0
  eslint-plugin-depend: ^1.4.0
  eslint-plugin-oxlint: ^1.28.0
  eslint-plugin-perfectionist: ^4.15.1
  eslint-plugin-prefer-arrow: ^1.2.3
  eslint-plugin-sonarjs: ^3.0.5
  fumadocs-core: 15.6.4
  fumadocs-mdx: 11.6.11
  fumadocs-twoslash: ^3.1.10
  fumadocs-ui: 15.6.4
  jiti: ^2.6.1
  lucide-react: ^0.553.0
  motion: ^12.23.24
  next: 15.4.1
  oxlint: ^1.28.0
  pkgroll: ^2.20.1
  postcss: ^8.5.6
  react: ^19.2.0
  react-dom: ^19.2.0
  remark: ^15.0.1
  remark-gfm: ^4.0.1
  remark-mdx: ^3.1.1
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.17
  tinyexec: ^1.0.2
  tsx: ^4.20.6
  tw-animate-css: ^1.4.0
  twoslash: ^0.3.4
  vitest: ^4.0.9
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
