name: check

on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 24
          registry-url: https://registry.npmjs.org

      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build
